sudo: required
language: generic
services: 
  - docker

before_install:
  - docker build -t sergiuoxigen/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true sergiuoxigen/react-test npm test

after_success:
  - docker build -t sergiuoxigen/multi-client ./client
  - docker build -t sergiuoxigen/multi-nginx ./nginx
  - docker build -t sergiuoxigen/multi-server ./server
  - docker build -t sergiuoxigen/multi-worker ./worker
  # Push images to docker hub
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push sergiuoxigen/multi-client
  - docker push sergiuoxigen/multi-nginx
  - docker push sergiuoxigen/multi-server
  - docker push sergiuoxigen/multi-worker
